### ISSUE TITLE
QoL: OoT Remove Unfair RNG elements from Fishing

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#100]
Vanilla fishing mechanics are just really, really, really bad. Even with the change you made to the reward requirement, a player can spend anywhere from as low as 1 minute to as long as 5-8 minutes trying to catch a fish due to the RNG the game has. This was fixed in OOTR and it should apply here as well.

Here is the relevant PR where they fixed it: https://github.com/TestRunnerSRL/OoT-Randomizer/pull/703

The other change made to fishing was putting a fish that meets the weight requirement for the reward on the left side of the pond for both child and adult away from any other fish. I'm not sure what commit or PR that was, unfortunately, and I checked the original AmazingAmpharos branch and couldn't find the relevant PR there either for this. But it definitely is a thing in OOTR in some commit! The RNG fix might be enough, though.

Edit: So here are the tasks for fishing.

- [x] Fix unfair fishing RNG such that the fish will always bite and won't break away from the line as per the linked PR above from OOTR.
- [x] Put an extra fish on the left side of the pond that meets the weight requirement to beat the record as both ages (so child has a 8 pound fish on the left side of the pond, adult has a 10 pound fish). Why the left side? There's not that many fish on the left side so you won't mistakenly catch a different weighted fish than you want.

Extra fish: https://github.com/OoTRandomizer/OoT-Randomizer/commit/80a558758ce2e87cc139210aade7b425b41c37df

**Comment by Nax** [comment]
Done
