### ISSUE TITLE
QoL: OoT Gerudo Fortress Changes (Gate + Minor Changes)

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#101]
- [x] Remove the "First Time Thrown in Jail" cutscene (PR for this here: https://github.com/TestRunnerSRL/OoT-Randomizer/pull/269 )

- [ ] Add a copy of the Guard at the bottom of the ladder that opens the gate.

- [x] Add another copy of the Guard to the other side of the gate to futureproof for ER and general QoL for getting caught when doing Reverse Wasteland *OR* in order to open the gate when you have Gerudo Card already if you forgot to open it from the other side or started with the card or anything.

Or something along those lines.

**Comment by Nax** [comment]
Do we need the guard at the bottom of the ladder? Does OoTR have it?

**Comment by Revvenn** [comment]
> Do we need the guard at the bottom of the ladder? Does OoTR have it?

OOTR does not have it but specifically because of the very purist, vanilla route they've decided with stuff like this. I only added this, though, because you mentioned it and it sounded like a nice idea to *not* have to climb the ladder every time to raise the gate. At the end of the day, up to you.

**Comment by Revvenn** [comment]
I don't really think we need the guard at the bottom, with the gate speed-up Celeste put in it's not as bad to climb up now tbh. If you ever change your mind, you're free to add it, but otherwise would rather other QoL happen before this.
