### ISSUE TITLE
QoL Setting: OoT Gerudo Fortress Behavior

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#103]
Like the title says. A drop-down setting that consists of the following:

Gerudo Fortress:
-Default Behavior (current functionality)
-Rescue One Carpenter (so only need to rescue the first carpenter, one key, and the Gerudo Card check activates after freeing the one carpenter)
-Open (the bridge is constructed, the player essentially starts with the Gerudo Card)

Can't find a PR where this was added to OOTR but the current setting can be looked at for OOTR in the main stable branch anyway.

**Comment by Nax** [comment]
How does it work with keysanity?
Right now the hideout keys are shuffled (as if it was a dungeon) even if obviously the shuffle doesn't change anything outside of keysanity.

**Comment by Revvenn** [comment]
In OOTR, for Open Fortress, they block you from shuffling the keys because the Open fortress setting basically gives you the Gerudo Card so the check is basically completed from the onset.

With One Carpenter, it's just the first carpenter that everyone normally gets. You have only 1 key and once you free that carpenter, you get the Gerudo Card check.

**Comment by Revvenn** [comment]
> How does it work with keysanity? Right now the hideout keys are shuffled (as if it was a dungeon) even if obviously the shuffle doesn't change anything outside of keysanity.

In OOTR, for Open Fortress, they block you from shuffling the keys because the Open fortress setting basically gives you the Gerudo Card so the check is basically completed from the onset.

With One Carpenter, it's just the first carpenter that everyone normally gets. You have only 1 key and once you free that carpenter, you get the Gerudo Card check.

**Comment by Nax** [comment]
Done
