### ISSUE TITLE
QoL: Add Another Connector from Hyrule <-> Termina

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#106]
Self-explanatory. Common suggestion is the most useless Lost Woods entrance (which is the very first one straight ahead) that typically loops you back to the beginning of Lost Woods.

I don't think this should be a setting that's toggleable but rather instead I think it'd be better to have it as a secondary entrance. Have it connect Lost Woods <-> ??? (maybe just have it take you to the Clock Tower anyway, not sure how that would work or if it's even possible). You would have to investigate this. Anyway, just another connector in general.

Anyway, goal of having both HMS and this connector would be that Adult Link would then have access to switching to Termina via Lost Woods while keeping the connector in Market for Prelude warp switches.

**Comment by Revvenn** [comment]
Do we really need this as an issue anymore? @Nax 

With cross warps and ER I really don't think we do.

**Comment by Nax** [comment]
One possible improvement it would have would be to bring back the HMS for more checks. Maybe with ER and cross warps, we could even have seeds without a "main" MM entrance at all? Low prio and a bit involved for sure.

**Comment by Revvenn** [comment]
> One possible improvement it would have would be to bring back the HMS for more checks. Maybe with ER and cross warps, we could even have seeds without a "main" MM entrance at all? Low prio and a bit involved for sure.

Problem is, you need to activate an owl before you can cross warp to MM unless you start with one of the owls as a starting item. So... not sure we could actually fully abandon a main MM entrance with that still being the case (where the only way to access MM otherwise on the user end is with starting with an owl activated).

**Comment by Nax** [comment]
> Problem is, you need to activate an owl before you can cross warp to MM unless you start with one of the owls as a starting item (or, if you add the pre-activated owl setting then whatever one you pre-activate). So... not sure we could actually fully abandon a main MM entrance with that still being the case (where the only way to access MM otherwise on the user end is with starting with an owl activated).

Yeah, this would require at least one of the following:

* Cross warps + owl shuffle
* Regions ER
* Interiors ER with extra interiors
* Dungeon ER with BtW and/or ACoI

**Comment by Revvenn** [comment]
Okay so returning to this conversation ... **again**.  Do we need this to be open still @Nax ? We have full overworld ER now (with a few exceptions but we basically _have_ it now). Do we still need to add another connector for Adult? Or, like, did you want to bring back the Happy Mask Shop (as a setting but only valid in ER) and basically your access to MM is whatever entrances you have available...? Do know that if you bring back HMS, the slots have to be shuffled by default and function like a free shop you can "borrow" the items from (or maybe the items are priced by how much you sell the original masks for?)

Or should we close this and not even think about it anymore?

**Comment by Nax** [comment]
With the cross game link I think we can close this, it will be able to be plandoed eventually.
