### ISSUE TITLE
QoL: Happy Mask Shop Entrance is Open at Night

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#107]
Self-explanatory. Makes going to Termina possible at nighttime without having to use Sun's Song or wait until daytime. Just adding as a TODO.

**Comment by Revvenn** [comment]
I think this would still be nice to do despite cross warps; if for whatever reason someone doesn't have cross warps enabled this is still pretty bad. Just making a note this is still relevant.

**Comment by Nax** [comment]
Agree, altho it should be an option IMO, as with some forms of ER (region ER specifically) the night/day of this entrance can be very logically significant in the earlygame.

**Comment by Revvenn** [comment]
> Agree, altho it should be an option IMO, as with some forms of ER (region ER specifically) the night/day of this entrance can be very logically significant in the earlygame.

Yeah sure, an option makes sense.

**Comment by CelestialKitsune** [comment]
Done in [0089be](https://github.com/OoTMM/OoTMM/commit/0089be983d72dd20e23d96df19bf1934f339a12a)
