### ISSUE TITLE
Setting: Ocarina Shuffle

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#112]
Basically what the title says. When turned off, the Ocarinas would be in their vanilla locations. I think, for now, you should have this as a setting for each game because MM's Ocarina otherwise would be on Skull Kid which isn't very ideal? Not sure. This setting would work better with a starting items customization where you could then force-start with MM's Ocarina and not worry about Skull Kid.

Anyway, it's a setting in OOTR so decided to put it here.

Edit: Since you added a pseudo-Song of Healing for Songs on Song Locations, maybe in this case we can add a pseudo-Deku Mask check for this? So that way, MM's Ocarina location doesn't require you to go to final hours just to get it when you turn off Ocarina Shuffle? You get it when you first go to MM, like the song check? At least until we have the ability to start with items proper and ocarina shuffle could be adjusted back accordingly?

**Comment by Nax** [comment]
I can add this for OoT (quite easy) but I cannot for MM - Skull Kid is not a valid location for MM Ocarina, as we need the ocarina in the first place to enter MM (and it's very hard to change that - see previous discussions on the discord)

**Comment by Revvenn** [comment]
> I can add this for OoT (quite easy) but I cannot for MM - Skull Kid is not a valid location for MM Ocarina, as we need the ocarina in the first place to enter MM (and it's very hard to change that - see previous discussions on the discord)

Honestly I made this suggestion before starting items and junking became a thing. I'm not sure if there's any value to have it? I suppose for people new coming in to playing combo it might be easier for them to see it as a setting for OOT but they might be confused why the setting doesn't exist for MM -- which is why it might be best to scrap this? Since starting items and junking (for the Ocarina of Time check, and if someone *doesn't* like the lost woods bridge fairy ocarina check they can junk that as well). Not sure...

**Comment by Revvenn** [comment]
I think I'm just going to close this. Anyone confused about ocarina stuff can always ask in the discord, most players who *want* an ocarina at the start of the seed will just use the starting items page. And if they don't want to deal with the lost woods bridge check or Zelda's ocarina from getting all stones, then they can just junk the checks (or plando OOT to be vanilla, or plando both ocarinas to be vanilla). There's lots of options and even for MM Ocarina. If something changes in the future we can revisit this, but seeing as its been so long and there's other features that basically *do* this I think we should just prioritize other things and forget this lol.

**Comment by Nax** [comment]
Actually I'm gonna add this (for OoT) as it is:
 * Very easy to add
 * Useful for random settings

**Comment by Nax** [comment]
Added
