### ISSUE TITLE
MM Setting: Shuffle Extra Scrubs/Merchants

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#122]
Basically what the title says. This is a setting you could make a simple checkbox that shuffles the following Scrubs and Merchants:

- [x] Gorman Bros. Milk (they sell milk on days 1, 2, and 3 in Milk Road if you aren't riding on Epona, this is something MMR has as an option to shuffle)
- [x] Southern Swamp Scrub that sells Magic Beans
- [x] Zora Hall Scrub that sells the Green Potion
- [x] Ikana Canyon Scrub that sells the Blue Potion
- [x] Milk Bar Milk and Chateau Romani

I couldn't think of a better way to categorize these shuffles so putting them under this setting made the most sense to me?

Edit: It would also be nice to have these affected by price randomization, should that be its own setting/toggle for shops and merchants.

**Comment by Revvenn** [comment]
Additional note: Should probably consider for the Canyon scrub blue potion to make it come back into your inventory on SoT reset when it has been found.

**Comment by Nax** [comment]
Added scrubs

**Comment by Nax** [comment]
Fully done
