### ISSUE TITLE
OoT: Ability to check Big Rolling Goron as Child without Bomb Bag

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#162]
Basically changing the Big Rolling Goron in Goron City to allow you to get his item without the Bomb Bag. OOTR changed this so this is just another thing to make it in parity so you can check this Goron with Bombchus. It's not game breaking at the moment since logically it requires Bomb Bag anyway but this is just another thing for 1:1 parity with the existing randomizer.

**Comment by Nax** [comment]
Done
