### ISSUE TITLE
MM: Remove/Shorten/Skip remaining cutscenes

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#182]
Decided to separate this out from the initial issue I made back in December so you can track this better.

**Tatl**
- [x] Remove Tatl Interrupts (made a separate issue for it #99 (just listing this here so it's tracked and the separate issue can be closed)

**Boss Intros**

- [x] Odolwa Intro Cutscene
- [x] Link looking around inside Goht's Boss Room Cutscene (the intro cutscene of thawing him is 100% needed but this small scene before that would be nice to be removed).
- [x] Gyorg Boss Intro
- [x] Igos Boss Intro (the boss in Ikana Castle, I believe this will require some complex hacking but MMR skips it to the point the two soldiers are spawned in as soon as you enter the boss room and the curtains are already down)
- [x] Captain Keeta ending cutscene, there _should_ be a flag for this to set since it can be repeated on subsequent cycles?
- [x] Stone Tower Temple Gomess Mini-boss Intro Cutscene (the mini-boss blocking the boss key chest on Inverted side)

**Region/Area Intros**

- [x] Southern Swamp First Time Visit
- [x] Deku Palace First Time Visit
- [x] Mountain Village First Time Visit
- [x] Goron Shrine First Time Visit (the area where Baby Goron is)
- [x] Great Bay Coast First Time Visit
- [x] Beaver Race Place First Time Visit
- [x] Zora Hall First Time Visit
- [x] Ikana Canyon First Time Visit
- [x] Pirate's Fortress Exterior First Time Visit (The trigger for this cutscene is not when you enter the area but when you walk up the slope and more onto the ledge ahead)
- [x] Pirate's Fortress Interior First Time Visit
- [x] Gorman Racetrack First Time Visit
- [x] Romani Ranch First Time Visit
- [x] Ikana Graveyard First Time Visit
- [x] Ikana Castle First Time Visit (the trigger for this cutscene is similar to Pirate's Exterior, walk out past the sun block and it triggers)
- [x] Stone Tower First Time Visit
- [x] Inverted Stone Tower First Time Visit
- [x] Woodfall First Time Visit
- [x] Woodfall Temple First Time Visit
- [x] Snowhead First Time Visit (area outside the dungeon)
- [x] Playing Goron Lullaby to the Big Goron in Snowhead First Time
- [x] Snowhead Temple First Time Visit
- [x] Inside Snowhead Temple there is a door that you walk out of to the main room where the central pillar is, a cutscene plays to show you the temple from the bottom to the top. Remove this scene probably by checking the flag for having seen it.
- [x] Playing New Wave Bossa Nova for the Turtle for the First Time, should be a flag for this considering it can be played on subsequent cycles and it skips the cutscenes once you've seen them.
- [x] Great Bay Temple First Time Visit (skipping the waving at the turtle scene, this scene is still there as of 1/16/23, it's possible it might be tied to the above cutscenes completely).
- [x] Shortened Woodfall Temple Opening Cutscene, MMR has a shortened version of the temple rising out of the poison water.
- [x] Stone Tower Temple First Time Visit
- [x] Inverted Stone Tower Temple First Time Visit
- [x] Clock Tower Opening Up at Midnight while waiting in South Clock Town (you can already "skip" this by waiting in another part of Clock Town or anywhere else in the world but it is a nice QoL to stand in front of the tower or come into SCT just as midnight rolls over without getting the cutscene). This works just like you have the Opening Door of Time Cutscene where the animation of the Clock Tower opening is playing during gameplay.

**Misc Cutscenes**

- [x] First Time putting Transformation Masks on cutscenes for each mask (Deku, Goron, Zora, FD)
- [x] First Time Boss Remain Warp Cutscene
- [x] Healing the Poe Cutscene for healing Pamela's Father (the really, really long cutscene when you play Song of Storms for the poe in Ikana Canyon)
- [x] Ikana Graveyard Song of Storms check cutscene (should maybe be a flag for this since it can be done on subsequent cycles? The curtains still rise as its own cutscene but after that, in MMR at least, you can get the check)
- [x] Various Scrub Leaving cutscenes; in MMR it works to where the scrubs leave during gameplay and the player is _not_ locked in place. This is what allows the Termina Field scrub to stay in the grotto in MMR to where if the player leaves before the scrub does then the scrub will stay in the grotto. There's one minor exception for the South Clock Town scrub where there is an initial cutscene camera of him getting out of the flower but once that ends control is given back to the player and the scrub is flying away during gameplay.
- [x] Song of Soaring, you already sped up the end/spawn scene so I'm not sure if it's necessary to speed-up the intro. I'll mark it as done for now.
- [x] Evan Piano Cutscene in Zora Hall
- [x] Woodfall area clear cutscene shortened (after beating Woodfall Temple) in MMR it fades out after the pan around the dungeon and skips the part where it raises the ramp to the Deku Princess location. Additionally remove the Deku Princess cutscene when you cut the vines, the player should just be able to scoop her after cutting the vines.
- [x] Skipping the cutscene or shortening it for when you drop-off the Deku Princess to the Deku King in order to access the Butler Race
- [x] Hungry Goron: Skipping the cutscene of him reacting to you bringing the Sirloin as well as skipping the cutscene of watching him roll away, in MMR for the latter it gives the player control while the Goron is rolling away (this isn't high priority though). The item give cutscene is still there, however.
- [x] Goron Village Owl - will not trigger dialogue when you go up to him, the player has to manually talk to him instead.
- [x] Aliens cutscene when you talk to Romani for the Epona's Song check, in MMR this cutscene is shortened where it skips the part showing you the aliens abducting the cow.
- [x] Skip the initial wagon riding cutscene with Cremia (the one that shows them going out of Romani Ranch to Milk Road and then Milk Road to Gorman Track). Just skip to the part when she asks you if you know what to do or whatever, the third part of the wagon ride basically.
- [x] Epona Cutscene in Romani Ranch when you do not have Epona's Song (just set the flag??? The cutscenes do not play when you already have Epona's Song). Though, you'll have to make sure Epona is still behind the gate so you can't just get her on day 3 for free.
- [x] Elegy of Emptiness Song Replay cutscene skip (so that when you play the song the statue spawns and you aren't sitting there watching it spawn)
- [x] Stone Tower Blocks moving faster (goes hand-in-hand with the above and they are essentially cutscenes anyway)
- [x] Apparently MMR shortened the death cutscene in MM, it goes to fadeout faster. MM's death cutscene is a bit long considering you can't speed it up like you can in OOT by immediately hitting the button prompts as they come up so I think this makes sense to carryover from MMR to OOTxMM if possible. It makes the small amount of death warps you might do a little more worthwhile. Edit (If this isn't too easy to do then ignore this task)
- [x] Pirate's Fortress Interior Hookshot Chest Cutscene - the one where the bees attack the pirates, in MMR this is shortened to where the bee comes out and the guards *do* run away but then they disappear faster and it results in the cutscene ending sooner. Not totally necessary as it only saves probably like 15 seconds? But if you can copy how it's shortened in MMR would be cool.

Hopefully this helps keep track of things better. I will also include the relevant sections for some of these from MMR below if it helps any.

https://github.com/ZoeyZolotova/mm-rando/blob/dev/assembly/src/Speedups.Patch.asm
https://github.com/ZoeyZolotova/mm-rando/blob/dev/assembly/src/Speedups.asm
https://github.com/ZoeyZolotova/mm-rando/blob/dev/assembly/c/ElegySpeedup.c
https://github.com/ZoeyZolotova/mm-rando/blob/dev/assembly/c/BusinessScrub.c

I'll make a separate issue for the mini-game speed-ups missing and stuff. I'll close/delete the old issue once I have.

**Comment by Celestial-Panda** [comment]
Trying to see which cutscenes are still left to shorten/remove...

* First time transformation
* PFI Hookshot chest - pirates
* Elegy speedup
* ST blocks
* Death cutscene

I am fairly sure the scrubs cutscenes have been properly removed besides SCT, which has been shortened just like in MMR

**Comment by Revvenn** [comment]
> Trying to see which cutscenes are still left to shorten/remove...
> 
> * First time transformation
> * PFI Hookshot chest - pirates
> * Elegy speedup
> * ST blocks
> * Death cutscene
> 
> I am fairly sure the scrubs cutscenes have been properly removed besides SCT, which has been shortened just like in MMR

Ah yes, you are correct. I'll update the task that it's fine (the scrubs), I forgot to do that lol.

**Comment by CelestialKitsune** [comment]
Last cutscene (pirates) done with [f5ce861](https://github.com/OoTMM/OoTMM/commit/f5ce861b9cd0c9f8ba8cca7e4c7df01da5c7fd9a)
