### ISSUE TITLE
MM: Bank Speed-up and QoL

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#184]
Splitting off from the issue I made in December.

- [x] Update the text to be accurate for the rewards at each threshold. It should say 500 rupees for the 1k reward and then 1k rupees for the 5k reward.
- [x] Pressing R when inputting the amount to Deposit/Withdraw will result in the amount of rupees in your wallet being input as well as factor in the fee when Withdrawing.
- [x] Pressing Z does the opposite of the above, putting the amount of rupees you're Depositing/Withdrawing to the lowest value (which is 0)
- [x] Some textboxes need to be skipped, such as the introduction to the bank where he gives you the "stamp" and all. MMR does this to where the first textbox plays (might just skip the whole stamp sequence as if you've talked to him already in the game) then the next is the one where you can start depositing money.
- [x] Every reward is given to you when you pass the reward thresholds all at once. Currently, the way it works is in order to make sure you get both the 200 and 500 rewards you have to first deposit for 200 *then* 500; if you immediately deposit 500 you will only the 500 reward. This is cumbersome because if you deposit *at or over* the reward threshold in order to get the previous reward (in this case, 200 rupees) you have to withdraw enough money to then deposit *back in* to reach the previous threshold to then get the previous reward. What should really occur is when you deposit 500 you should get both the 200 and 500 bank rewards. And if you deposit above 500 (if you were at like 450 rupees) and get to 1000 you should get both the 500 and 1k rewards.

Here are the relevant spots in MMR to look at for how it was done.

Multiple bank rewards given out: https://github.com/ZoeyZolotova/mm-rando/blob/dev/assembly/c/GinkoMan.c
Bank R/Z Inputs: https://github.com/ZoeyZolotova/mm-rando/blob/dev/assembly/c/Input.c

**Comment by Celestial-Panda** [comment]
https://github.com/ZoeyZolotova/mm-rando/blob/dev/assembly/c/BankAmount.c
https://github.com/ZoeyZolotova/mm-rando/blob/dev/assembly/src/BankAmount.asm
https://github.com/ZoeyZolotova/mm-rando/blob/dev/assembly/src/BankAmount.Patch.asm

Updating the important links for R/Z inputs

**Comment by Revvenn** [comment]
Completed: https://github.com/OoTMM/OoTMM/commit/f213122250b4f50dada60be81d7de4d4cf131637
