### ISSUE TITLE
MM: Pictograph Box Improvements

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#185]
Splitting this off from the issue I made in December.

- [x] The textbox for "Keep this picture?" needs to denote what the picture is of to indicate to the player they took the correct photo. For example, it needs to say "Keep this picture of Tingle?" when you have gotten the correct picture of Tingle. "Keep this picture of Big Octo?" "Keep this picture of Deku King?" "Keep this picture of the Swamp?" (to be clear, Deku King is the same as Tingle for the reward but the other 2 are futureproofing for when you decide to shuffle the rupees for those respective photos).
- [x] The textbox also needs to account for Lulu photos and the Pirate photo and these differ from the above. The textbox in MMR, I believe, goes something like "Keep this good/bad picture of the Pirate?" "Keep this good/bad picture of Lulu?" This helps with getting the correct photo for the Seahorse from the Fisherman. And for Lulu, it would just be futureproofing for whenever you decide to shuffle the rupees when handing the photos of her to the Zora in Zora Hall.

Relevant spots for this in MMR if it helps.

https://github.com/ZoeyZolotova/mm-rando/blob/dev/assembly/src/Pictobox.Patch.asm
https://github.com/ZoeyZolotova/mm-rando/blob/dev/assembly/c/Pictobox.c

**Comment by Nax** [comment]
Done
