### ISSUE TITLE
OoT: Skip/Shorten some Boss Death Cutscenes

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#186]
These are the remaining boss cutscenes that need to be skipped/Shortened in OoT:

- [x] Twinrova Arguing
- [x] Ganondorf death cutscene and the brief intro scene to the Ganon fight that follows after (when Link and Zelda are talking a bit, OOTR skips right to when you have control of Link after the pan over the wreckage of the Castle)
- [x] Phantom Ganondorf death cutscene

**Comment by Nax** [comment]
Done
