### ISSUE TITLE
QoL: Gorons as Adult returning to Goron City Behavior (instead of Fire Medallion it should be Fire Temple cleared)

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#207]
This is a ridiculously minor thing but OOTR changed this behavior so I guess we have to here as well. Basically, instead of the Gorons populating Goron City as Adult when you have the Fire Medallion they should only do this when you have Fire Temple cleared. This only really matters because there's one Goron on the platform near the Skulltula and he kind of gets in the way of getting it when you don't have Hookshot (you can still get it, it's just weirder with how you have to backflip earlier).

**Comment by Nax** [comment]
Done
