### ISSUE TITLE
OoT: Pause Menu should default to Inventory screen not Overworld Map screen

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#214]
What it says in the title.

**Comment by Nax** [comment]
Did you not create a ticket for this already?

**Comment by Revvenn** [comment]
I didn't I'm pretty sure...???

**Comment by Nax** [comment]
My bad then

**Comment by Revvenn** [comment]
It's all good lol. I told you about it but just didn't make it an issue since it's very, very, very minor.
