### ISSUE TITLE
QoL: Ability to Raise/Lower Lake Hylia Water Level for Entrance Randomizer

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#224]
In OOTR there is a Gossip Stone placed in Lake Hylia, in a specific spot to avoid ruining glitch/trick setups, which allows the player while slashing their sword at it to raise/lower the water level of Lake Hylia when you have killed Morpha.  Since the water level has been moved to be tied to the dungeon cleared at Water Temple, then this gossip stone should reflect that when created. The purpose of this stone is for the Gold Scale Entry logic with ER, to prevent softlocks especially useful for dungeon ER and full ER.

Refer to where OOTR placed it specifically because I don't have any idea on exact coordinates or anything haha.

Edit: Maybe this should be a wisp you interact with instead of a gossip stone you slash?

**Comment by CelestialKitsune** [comment]
Done by https://github.com/OoTMM/OoTMM/commit/ace756939b3e0569ca17e42a5047bb12ac32e2ae
