### ISSUE TITLE
Cosmetic: Items having the correct item fanfare

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#226]
So this is a very super minor detail but both OOTR and MMR did this, I'm not sure how possible it is to do since you made it so chests believe they have their vanilla contents (actually, this also happens with NPCs anyway too so I think it's just the items themselves?) But basically, what this issue is is that when you get a blue rupee from a chest/NPC it should play the minor get item fanfare instead of the major one like it does right now with some chests/NPCs. Likewise, when you get a major item from a chest it should always play the major get item fanfare (I haven't noticed any major items not play the major item fanfare so I think this is fine already). However, I do know that with minor items like money, ammo, etc it's not consistent on whether it plays the minor fanfare or major fanfare so that's really what needs to be changed.

A quick example I can give is probably in MM's lens cave, if you go over to the invisible chest and pick up a rupee from that chest I believe right now it will still play the major item fanfare instead of the minor one. It's just a minor _odd_ thing and if it's not doable with how chests behave right now then no big deal.

Edit: I think this applies across the board to chests, NPCs, and freestandings right now? Not 100% but feel like it does. It's super minor either way, though.

**Comment by Nax** [comment]
I think the issue actual is that the fanfare is not correct for foreign items.

**Comment by Nax** [comment]
Added
