### ISSUE TITLE
QoL: Lower the collision of the Forest Temple first switch in the Basement

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#230]
In Forest Temple there's a switch in the basement where you push the walls around, the very first switch has bad collision in that needs to be lowered by some units or something. I can't find the original PR for this for OOTR but basically the issue is that you can't walk directly onto the switch very easily due to how high the collision is. Many people are used to how it is in OOTR for this switch.

**Comment by Nax** [comment]
Done
