### ISSUE TITLE
QoL: Let the Talon cutscene in Hyrule Castle run "in-game" like Door of Time opening

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#231]
This was a cutscene I forgot was technically "skipped" in OOTR by making it so there's no cutscene camera and Talon still runs away after talking to him once you've woken him up with the Chicken. This is ultimately SUPER minor, though.

**Comment by CelestialKitsune** [comment]
Done in [369a662](https://github.com/OoTMM/OoTMM/commit/369a662c5b553eb7dbbec71baef47d7044dc1af6)
