### ISSUE TITLE
Bug: C-Up Tatl trigger near Great Bay Coast Fence without Epona's Song is gone

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#233]
This specific Tatl interaction is very niche-ly useful when you don't have Epona's Song in MM as activating this also triggers the bean outside Observatory to appear, making it already planted. It's used in order to check the TF scrub after spawning it from Observatory when you don't have any other faster methods to do so. But the Tatl text only appears for it when you don't have Epona's Song.

This was, unfortunately, incidentally removed in the apocalyptical Tatl Interrupts removal. If this one trigger could be restored at some point that would be nice.

**Comment by Nax** [comment]
Fixed
