### ISSUE TITLE
Setting: Dungeon Stray Fairies Removed/Start With

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#240]
You said you would do this at a later time but basically a setting for Stray Fairies that either removes them from the pool _or_ you start with them like maps/compasses. Whichever direction you choose to go, all the stray fairy checks are then shuffled and the fairy fountain rewards are able to be gotten for free. And they (they being the stray fairies) are replaced by random junk in the pool.

**Comment by Nax** [comment]
Added
