### ISSUE TITLE
Setting: Small Keys and Boss Keys Removed (aka Keysy)/Add Small Keys and Boss Keys to Starting Items

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#241]
A key shuffle setting for both Small Key and Boss Key settings that removes the locks on the doors and deletes the respective keys, random junk replaces the deleted keys in the item pool. Meant to be an easier key shuffle setting but it's actually quite popular for MM dungeons (specifically the Small Keys variant). Obviously these would be available in the individual drop-down menus for each key type.

Would also be nice if this was added that the key settings were split for each game like every other setting is currently.

**Comment by Nax** [comment]
Done (with keysy)
