### ISSUE TITLE
Dungeon ER: Additional access to dungeons

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#265]
As suggested, moved these to a new issue.

- [x] Deku Tree needs three different settings for its behavior but one of those three is  a default to dungeon ER. In the sense that, when dungeon ER is on, Deku Tree is accessible to both child and adult Link (so Deku Tree's mouth is open as adult). So that by itself needs to be done. The actual setting, however, to make it so Deku Tree is more "balanced" is to make a Closed setting where Mido is restored to blocking the Deku Tree as child Link; checking for your Kokiri Sword and Deku Shield. Once you've acquired both and talk to Mido with them equipped, Mido will be moved and the Deku Tree's mouth will be opened for Adult Link (it is closed until Mido is moved in this setting).

If you need the PR that created Closed Deku Tree, you can see it here: https://github.com/TestRunnerSRL/OoT-Randomizer/pull/803

- [x] Bottom of the Well needs its water to be drained by child with Song of Storms so adult can access the Well entrance. So the Well draining needs to take effect for Adult Link. Only when Dungeon ER is active.
- [x] Fire Temple needs Child access by way of getting rid of the Silver Boulders blocking it. Whether you just remove those completely or remove them and place small rocks in their place (OOTR did this) is up to you; the latter is more an aesthetic thing. Again, also only active when Dungeon ER is on.

All three of these are to allow more Spirit Temple freedom but also less restrictions in general.

**Comment by Nax** [comment]
Done
