### ISSUE TITLE
QoL: Adult MM Access

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#271]
Putting this up here as a TODO. Probably a door somewhere in Market (could be in the very same spot as where HMS is as child)/ToT for Adult to walk through to get to MM? Or an NPC you talk to (Sheik?)

**Comment by Nax** [comment]
I think this needs more discussion now that we have cross game warp / ER that does mostly the same thing

**Comment by Revvenn** [comment]
> I think this needs more discussion now that we have cross game warp / ER that does mostly the same thing

Yeah I'm not sure it's entirely necessary? Probably the only instance you'd need it is for those who would be masochistic enough to not turn on cross song of soaring. But I really think that's less than 1% of people who would do that. I'd probably say just cater to the majority on this and not worry about having a base-game-adult-access-point basically. But I'll let you decide if this issue should remain open.

**Comment by Revvenn** [comment]
So some more time has passed, have your thoughts changed about this any @Nax ? This can be closed if you feel we don't need this at this point with cross game warp / ER. I, personally, don't think we do as I sort of indicated above and this will only end up really being usable in non-ER. I think the only way this would need to exist is if the HMS entrance was ever removed and you don't have cross game warps enabled. But even then ... I don't think Adult Link needs access without cross game warp as most people probably will enable some of ER in their seeds?

It's all just guessing right now but the time spent on implementing a custom actor _somewhere_ in the game adult has access to is probably better spent on other things.

**Comment by Nax** [comment]
Closing as it's not really required rn
