### ISSUE TITLE
QoL: Keaton Mask in OoT is misspelled as Keatan Mask in the inventory screen

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#278]
This is a vanilla 1.0 bug but it's been brought up a few times you might as well fix it when you can. It's _only_ on the inventory screen, just a localization error in 1.0.

**Comment by Nax** [comment]
Not really a bug IMO, eventually I may want to change it.

**Comment by Celestial-Panda** [comment]
Found the related pull request from OOTR - https://github.com/OoTRandomizer/OoT-Randomizer/pull/523
But I have no way to read the .bin file used for now

**Comment by Nax** [comment]
Fixed
