### ISSUE TITLE
Bug: MM without magic meter induces slightly off-color font outlines on the HUD

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#285]
Self-explanatory and SUPER minor bug. It colors the font for C-button stuff like bombs and arrow counts outlines green instead of keeping their black outline and such. It fixes itself once you get a magic meter.

**Comment by P3rf3ctXZer0** [comment]
no such thing as a minor bug - good eye 🗡️

**Comment by Nax** [comment]
Fixed
