### ISSUE TITLE
ER: Move the Woodfall Clear Flame to near the Owl Statue in front of the Boat Cruise and Zora Cape's to Great Bay Coast Owl

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#333]
Figure I'll put this here so it doesn't get lost/forgotten. The current location for the flame to make it cleared Swamp is rather inconvenient because if you only have Deku Mask it will take a very long time to get around to the entrance of Woodfall to touch the flame (either bottle or just a projectile even). The suggestion is to move the flame to near the owl statue in front of the boat cruise instead in Southern Swamp.

- [x] Southern Swamp Wisp move to near Tourist Center
- [x] Great Bay Wisp move to Great Bay Coast Lab

**Comment by Revvenn** [comment]
Probably also extend this to the Great Bay's clear wisp to be moved from Zora Cape to Great Bay Coast.

**Comment by CelestialKitsune** [comment]
Fixed by [f84282](https://github.com/OoTMM/OoTMM/commit/f84282135074cc84b82fd1e0abcb6429d856bfe5) and [31f8d4](https://github.com/OoTMM/OoTMM/commit/31f8d409fd062782a036067be59a765ea1e1373f)
