### ISSUE TITLE
Bug: Shared magic meter being drained during OOT > MM game transitions if you do them fast enough

### ISSUE THREAD

**Issue by ZeeMaji** [OoTMM/OoTMM#335]
When initially loading a save file in OOT the magic meter has this animation where it slowly fills back up.
Normally this doesn't affect anything but with shared magic enabled if you initiate a transition to MM (through song of soaring or cross-game entrance randomizer) before it finishes filling up then it will result in the magic meter being empty or having less magic in MM than you really had in OOT depending on how fast you start the transition.
Video demonstration, first is soaring to MM before the meter fills up and the second is soaring after it fills up.

https://user-images.githubusercontent.com/42477864/227481501-178af42e-823e-49e0-9721-49a5e1588955.mp4

This might happen when going from MM to OOT as well but the magic meter animation was greatly sped up in MM so it seems a lot harder to trigger there.

**Comment by Onemario1234** [comment]
The best fix I can think of for this, which would also make the transition between games a bit seamless, is to simply remove the animation outright and have the Magic Meter start at whatever value it last was, like the transition from OoT to MM.
