### ISSUE TITLE
Bug: Entering areas where Epona is not allowed in MM crashes the game (Region Shuffle)

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#366]
Self-explanatory. This needs to be fixed for entrance rando. If you enter Ikana Canyon or Mountain Village from an entrance Epona can ride into the game will crash but I'm sure there will be more areas that can crash if this isn't addressed before full OW ER is done. May have to try and copy what vanilla OOT does which according to AA is just forces you to be dismounted from her in the scenes where she isn't allowed. Just totally despawn her.

**Comment by Nax** [comment]
Finally fixed
