### ISSUE TITLE
Pausing still crashes ROM in OoT when using the ParaLLEl plugin

### ISSUE THREAD

**Issue by 03bgood** [OoTMM/OoTMM#387]
I'm using a Steam Deck with the RetroArch Mupen64Plus-Next core and the game crashes if you try to open the inventory menu in OoT, in most places. This seems to happen with ParaLLEl. It doesn't with GlideN64. The pause menu works but it's very glitchy and the background has is a rainbow color mess.

**Comment by Nax** [comment]
Don't use ParaLLEl - it's not supported. Use GlideN64 instead. The rainbow thing is unavoidable as far as we know, unfortunately.

Also, the github issues are for project management and bugs, not for tech support. These questions would be better answered in our discord: https://discord.gg/4QdtPBP6wf

**Comment by 03bgood** [comment]
I've found the issue, it when you pause the game whenever the minimap is displayed the lower left corner of the screen, it will trigger the crash. If it's disabled, then you can pause the game without it crashing, this happens in both the overworld and dungeons.
