### ISSUE TITLE
Minimap HUD is causing the game to crash in OoT

### ISSUE THREAD

**Issue by 03bgood** [OoTMM/OoTMM#392]
I've found the issue to why OoT crashes whenever you bring up the inventory; it's when you pause the game whenever the minimap is displayed the lower left corner of the screen, it will trigger the crash. If it's disabled, then you can pause the game without it crashing, this happens in both the overworld and dungeons. Hopefully the devs know about this and it can be fixed in the next update.

**Comment by Nax** [comment]
It's a ParaLLEl issue - don't use that, as previously mentionned. It's buggy and unsupported. Also this is not the place for this, use our discord instead, and don't re-create closed issues.
