### ISSUE TITLE
Setting: Split up Shared Masks into their own Individual Options

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#394]
Just like you did with Songs and the elemental arrows, split up the shared masks so players can decide which ones they want to be shared. Mostly useful for special conds. if say you wanted Goron and Zora shared but not Bunny Hood or Keaton Mask. Also may be nice for whenever selling masks to the people is a setting? So you can decide to have Goron and Zora shared but not the others since they would be actual checks.

**Comment by Nax** [comment]
Done
