### ISSUE TITLE
Vanilla Bug (kind of): MQ Fire Temple Like Like permanently eats shields

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#395]
This is an issue with only this Like Like specifically. For some reason it eats shields permanently and the devs seemingly knew about it, putting a Hylian Shield in the chest nearby it. This behavior is unlike other Like Likes in the randomizer and was fixed in OOTR so probably should put that same fix in for this Like Like as well. It's the Like Like right at the start, in the room where the Boss Key chest is in vanilla Fire Temple.

One of the only other MQ fixes applied that we overlooked in its implementation, it's minor but would make sense to bring it in line with the other Like Likes.

**Comment by Nax** [comment]
Fixed
