### ISSUE TITLE
Bug: Hyrule Field music does not transition to proper states when switching games

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#400]
This has been noted in the Discord, just noting it here. When you return from MM, Hyrule Field music does not ever go into its calm state when Link is standing still. Also apparently combat music doesn't play sometimes when coming back from MM? Not sure on the latter but it's a thing.

Probably more easily fixable when Owl is done merging the audio tables. Just thought I'd note it down here, though.

**Comment by Nax** [comment]
Is it only when coming back directly to Field from region ER? As in, leaving the scene and then coming back fixes it?

**Comment by Revvenn** [comment]
> Is it only when coming back directly to Field from region ER? As in, leaving the scene and then coming back fixes it?

I don't really know lool. Ghunzor would know better, I think, seeing as he was the one who brought the issue up.

**Comment by Revvenn** [comment]
I'm not sure anyone cares about this after custom music was added so even if you **did** fix this issue, nobody would notice because 95% of players are using custom music probably. It's kind of silly though because this _is_ an issue but it's so minor and if the solution is "using custom music, you won't ever hear hyrule field" then it's probably better for it to be that than keeping this issue open and having you use up valuable time investigating this weird audio thing that only Ghunzor has really ever pointed out lol. (Because I sure as hell did not notice it)

**Comment by Nax** [comment]
Fixed
