### ISSUE TITLE
Bug: Blank B glitch in Region Shuffle when riding OOT Epona into a shuffled loading zone

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#401]
What it says in the title. If you ride Epona into a shuffled loading zone in the overworld, the next time you come back to OOT, all of your equipment and items will be unequipped from Link. In turn, you will lose your sword on your B button because of it so if you are riding Epona with Master Sword on your B button... you lose your Master Sword and are effectively swordless (you cannot reequip it). You still "have" it but it's not actually there on your B button. Making the seed unbeatable.

This is a critical issue as it can lead to seeds being unintentionally unbeatable if someone doesn't know about this.

**Comment by Celestial-Panda** [comment]
Fixed by [0c43c0b](https://github.com/OoTMM/OoTMM/commit/0c43c0b3cc3bedb4b839e6a70283b6f3bc954a66) and [7fe562](https://github.com/OoTMM/OoTMM/commit/7fe562ef9ec753e117b900041ba2d35105279c22)
