### ISSUE TITLE
QoL: Update Trade Items on C buttons and show the next Trade Item in Sequence in Inventory

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#402]
Currently, if you press L or C-up to switch trade items while you have a trade item on a C button you have to reequip the trade item. This is technically *fine*, but I think it would be cleaner if the trade item updated on the C-button it's equipped to so the player doesn't have to reequip when wanting to switch trade items. This should apply to child, adult, and MM trade items. This also is technically preparation for the possibility of adding child trade items to D-pad right (if ageless items are not turned on).

Secondly, it would be nice if when you have multiple trade items on a slot it would show the next trade item in sequence at a smaller size *next* to it. MMR has this implemented for its trade item system and I think this would help communicate to new players that they haven't *lost* their trade item or have had it overwritten. The different colored icon isn't doing enough to communicate to new players, we still get questions about it every so often.

- [x] Update C-button trade items when switching trade items
- [x] Add smaller sprites of the trade items, right next to the current trade item, to indicate the next trade item in sequence (and that you have more than one).

Example of task 2 (look at the Mountain Title Deed and Swamp Title Deed slot): 

![Image](https://user-images.githubusercontent.com/40970119/235552850-f50b823e-2cf2-4bd5-a097-c24be21791d8.png)

**Comment by Nax** [comment]
This is annoying to do with cross game icons. Do we really want that? As a compromise we could have a little "L"/"C-Up" icon when over a slot where this is possible, to avoid the !trade noob trap.

**Comment by CelestialKitsune** [comment]
Done by https://github.com/OoTMM/OoTMM/compare/4c72d47a3f4c...04e2f79439f8
