### ISSUE TITLE
Setting: MM Owl Warp Points as Items

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#405]
What it says in the title. Was suggested in the discord, it sounds like an interesting idea. You basically shuffle the Owl Warp Points as items, maybe using a smaller Owl Statue model to represent them? And they would basically act as equivalents to OOT Warp Songs in a sense, except once you collect them they activate the Owl Statue it is tied to, giving you potential access to an area you **might not** have access to. I.E You find the Stone Tower Owl Warp Point, it activates Stone Tower Owl and you don't have MM Hook/Garo/Gibdo/Ice Arrows and suddenly you have access to upper canyon and STT without any of those items.

This could also pair well with Entrance Rando of some forms, whether Region Shuffle, Dungeon ER, or the fuller OW ER later on.

**Comment by Nax** [comment]
Added
