### ISSUE TITLE
QoL: Auto-advance Credits Textboxes

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#406]
What it says in the title. Both OOT and MM have textboxes that need the player to press A to advance. Both solo randomizers have made it such that those textboxes advance automatically and it can be kind of nice to let them go automatically while the player is able to go look at the spoiler log and what not. Very small cosmetic/QoL thing.
- [x] OOT
- [x] MM

**Comment by CelestialKitsune** [comment]
Done in https://github.com/OoTMM/OoTMM/commit/6426b55268991cd411adb72448771fb5969eb905
