### ISSUE TITLE
Bug: MM Ocarina is disabled in town interiors when on a C-button

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#408]
I didn't go to confirm this myself today but Jeville reported this on discord in #dev-talk (https://discord.com/channels/1004394204992118935/1009157440249536574/1102313606957256784) randomly so I guess I'm gonna put it up here right now. Vanilla behavior allows you to use Ocarina in any town interiors like the d-pad ocarina does.

**Comment by Nax** [comment]
Is this still an issue?

**Comment by Celestial-Panda** [comment]
Just tested every interior in Clock Town, with Ocarina of Time, it was never disabled.
However, Fairy Ocarina is disabled

**Comment by Nax** [comment]
Was the fairy oca also disabled on the dpad?

**Comment by Celestial-Panda** [comment]
No, and that's what's curious about it

**Comment by Nax** [comment]
Fixed
