### ISSUE TITLE
Bug: Mido wont let me back into Deku Tree

### ISSUE THREAD

**Issue by 03bgood** [OoTMM/OoTMM#409]
I was able to earlier, but now Mido just blocks the way. I don't know what happened but he won't let me pass. I hope this isn't a softlock! I'm not good at doing glitches.

**Comment by 03bgood** [comment]
After getting the Kokiri Sword, he still doesn't move. Had to use a GameShark code to Moon jump past him.

**Comment by Revvenn** [comment]
The github issues page is for confirmed, reproducible bugs. I'd suggest joining the OOTMM discord and posting a thread in the bug-reports channel following the template listed in the channel: https://discord.gg/4QdtPBP6wf

(And be **very** specific about what happened, posting the spoiler log, and everything listed in the template).

**Comment by 03bgood** [comment]
No, it has nothing to do with the core, it's one of the game's event flags, probably.
