### ISSUE TITLE
Region ER: Add Desert Colossus

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#419]
Title is self-explanatory. Haunted Wastelands is kind of a path or road so it would make the most sense to shuffle Desert Colossus into the pool of overworld regions. It's probably the last one for this setting? Not sure. But I feel it would be very interesting having Haunted Wastelands lock a MM location or even an OOT one like Kakariko Village (as unlikely as it would be).

**Comment by Nax** [comment]
I think we need a fix for the sandstorm effect before we can add that?

**Comment by Revvenn** [comment]
> I think we need a fix for the sandstorm effect before we can add that?

If that is the case, here's the PR: https://github.com/OoTRandomizer/OoT-Randomizer/pull/1299

**Comment by CelestialKitsune** [comment]
> > I think we need a fix for the sandstorm effect before we can add that?
> 
> If that is the case, here's the PR: [OoTRandomizer/OoT-Randomizer#1299](https://github.com/OoTRandomizer/OoT-Randomizer/pull/1299)

I tried to implement it, I ended up on a black screen when loading up a seed 🙃 but without the fix, it's extremely bad

**Comment by CelestialKitsune** [comment]
Done somewhere in https://github.com/OoTMM/OoTMM/compare/30fa8045ca09...8b643511860d
