### ISSUE TITLE
Setting: Woodfall Temple and Great Bay Temple access in Cleared Region states

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#421]
Similar to the Adult and child access settings for Well/Fire Temple/Deku Tree, these settings would allow the player to access Woodfall Temple in cleared Southern Swamp **without** Sonata of Awakening with the dungeon already raised.

Likewise, for Great Bay Temple, if Great Bay is in its cleared state then the turtle is already raised and hookshottable **without** New Wave Bossa Nova.

Essentially creating similar logical similarities to spring time access for the Snowhead Temple dungeon **without** Goron Lullaby.

**Comment by Nax** [comment]
Done
