### ISSUE TITLE
Setting: Pre-activated Owl Statues

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#426]
Using the work you did on Owl Statue Shuffle, it would be nice to have a separate setting that allows you to set what Owl Statues you want to be active from the start of the seed and have the logic take it into account. The current setting where you could start with them as items and what not has some additional baggage (such as getting items from the owl statues anyway even if you junk the ones you start with to have them pre-activated) so not having that going on and just having this as its own setting would be great. You did say you would do this so adding it here.

**Comment by CelestialKitsune** [comment]
Done in https://github.com/OoTMM/OoTMM/commit/2741590ed991d7c868c3e63e6733b9488eed913f
