### ISSUE TITLE
Bug/Unintended?: Warping to OOT with Hot Spring Water instantly cools

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#427]
What it says in the title. I'm not sure if this is intended or an actual buuuug or just a side effect of how the HSW timer is handled in MM, but if you warp from MM while you have HSW to OOT -- even if it's right at the beginning of when you've picked up HSW -- it cools instantly when you come back to MM from either soaring in or going through the Happy Mask Shop.

I think the behavior should be: pause the HSW timer until you return to MM, much like how the clock works when switching between games. If such a thing is even possible, anyway. This way, you could have HSW carried through OOT and it could be really interesting in future ER shuffles and what not. Hell, right now it would be useful for depending on where Snowhead Temple ends up.

**Comment by Nax** [comment]
Fixed in ER with the perma-HSW
