### ISSUE TITLE
QoL: OOT Fast Armos Statue Pushing

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#429]
What it says in the title. OOT has some Armos statues that players use for some tricks and casual players may appreciate the instances they need to move the Armos statue (such as in Dodongo's Cavern for the switch on 2F). This recently got a PR in OOTR that is probably being merged: https://github.com/OoTRandomizer/OoT-Randomizer/pull/1981

**Comment by Celestial-Panda** [comment]
Closed in #439
