### ISSUE TITLE
Behavior: Shop Pre-Conditions that need to be restored

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#440]
This issue relies on everything with shops being kinda done in terms of changes to them but I thiiiink right now they are in that state besides price randomization? Anyway, since shop shuffle settings were introduced many shop pre-conditions had to be removed to make it work; some of these pre-conditions need to eventually be restored, however.

- [ ] Currently, buying deku sticks specifically produces a GI animation for every stick and copy of the item you buy. In vanilla, as long as you don't already have the item in your inventory, the GI animation will play once and then every subsequent purchase it will skip the GI animation. At least, I **think** that's the case? The issue really is that the GI animation right now plays for every and any purchase you make, regardless of if you already bought the item in the shop once.
- [ ] However, the exception to the above rule, is Bottle Contents do not play GI animations at all when buying from shops. So Red Potions, Bugs, Blue Fire, etc. At least, in MM they don't, maybe in OOT they do?
- [ ] Further relation to bottle contents, another pre-condition that needs to be restored is checking for if your bottle is full so you don't end up mistakenly purchasing a potion or the like with a full bottle.
- [ ] In MM, the Witch's Potion Shop Blue Potion slot currently charges you 60 rupees once you've sold the mushroom to her. However, in vanilla, the first blue potion is free (she says it's a free sample). Every purchase after that first free sample is then actually 60 rupees. So the vanilla behavior of it being a free sample needs to be restored.
- [ ] Hylian Shield Discount from the Bazaars, when you've received Zelda's Letter (or met Zelda?) needs to be restored as well.

I believe these are the pre-conditions that need to be restored? Can't think of anything else right now. Can always add more to this issue if more are thought up.

**Comment by Nax** [comment]
Done, except for the free sample and discount.

Free samples need to be handled globally (free MM bean and free MM red potion refill from koume), and it's kinda difficult to integrate that with logic properly.

The discount is random and applied once you show zelda's letter to the guard. It's not trivial to add that behavior back but it's doable, it may have logic implications in price rando tho.
