### ISSUE TITLE
Swamp Witch Potion Shop and Mountain Smithy will kick you out to original regional locations even in Interior ER due to unique kick out triggers

### ISSUE THREAD

**Issue by ZeeMaji** [OoTMM/OoTMM#460]
Just ran into this in a seed i was doing, during the final night the swamp potion shop will still be open. But if you try to interact with anything you will get a message about how the keeper is out running errands and it will automatically kick you out of the shop into southern swamp, even if the swamp potion shop interior is somewhere else entirely in interior ER.

**Comment by Revvenn** [comment]
Just leaving an additional note here that there are other special kickouts that have not been handled yet either and include the Smithy, where when you talk to him and *do not* have gold dust he will kick you out. Might also be the case for the first one as well, when you don't have the money to do the first reward. So it may be both instances.

Other than those, I don't think there are *any others* in MM like that. I've also edited the title to reflect this as it's not just the witch potion shop.

**Comment by Nax** [comment]
Can't seem to get kicked by smithy, even when not having gold dust

**Comment by Nax** [comment]
Fixed
