### ISSUE TITLE
Bug: Pulling out Ocarina (from D-Pad down) and putting away in Bombchu Bowling (in OOT) crashes the game

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#484]
Pretty self-explanatory title. Since there's no restriction for D-pad Ocarina, you are able to pull it out inside the Bombchu Bowling building and when you do so *if* you put it away (or hell, maybe if you even try to warp out, I didn't try) it crashes immediately. The solution to this issue is to just restrict the Ocarina in there like in the Treasure Chest Game. Not sure how this one even went missed as a restriction, nor how no one else ran into this crash (I guess most players just leave the building to warp away). This is a vanilla crash because even for OOTR when the restriction was lifted temporarily (a very short time) players ran into crashes so it was re-restricted lol.

**Comment by CelestialKitsune** [comment]
Fixed by [294da26](https://github.com/OoTMM/OoTMM/commit/294da263c58c78acf469d0162bdd651b47512e10)
