### ISSUE TITLE
Setting: Silver & Gold Scale in MM + Shared Scales

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#488]
I think if we want to maybe do more item extensions for MM, this *could* be a small fun addition. I don't know how possible it is to do but it would be nice to have these and then be able to have a setting called "Shared Scales." It would have seldom use in MM but the few places it *could* be used would change some logic for a few checks like the Bio Baba Grotto being able to be gotten with the Gold Scale (maybe even Silver?) And like, human being able to access the Pirate's Fortress entrance in cleared Great Bay in the cases where FD is used to defeat Gyorg (or if you have an OOT boss in GBT).

You could also then have MM Link with this able to go through the STT water tunnel with Silver Scale and that would change STT logic a bit, too. I think it'd be great to have more items shared between them like this, where it makes sense. And this makes sense to me and may not even be too bad to do?

**Comment by Nax** [comment]
Done
