### ISSUE TITLE
Bug: Goron Rolling and Zora Swimming with Random Tunic Colors are missing colored parts

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#493]
This isn't really a bug, per se, but I wanted to file this here so it's not forgotten. When you Goron Roll and your Goron hat color is different the Goron Roll hat is still green, its vanilla color.  Likewise, when Zora is swimming its Fins are its vanilla green color as well. These are the only missing colored textures, I believe, with random Goron and Zora tunic colors.

**Comment by Nax** [comment]
Fixed
