### ISSUE TITLE
Bug: Blank B sword in OOT in entrance rando settings

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#496]
This apparently happens somewhat very rarely where if you swap games a lot during entrance rando (due to the shuffled entrances) you have a chance of losing your B sword? It can be any sword on your B button in OOT so Kokiri Sword, Master Sword, or Giant's Knife/Biggoron Sword. Just putting this here right now as it is an issue worth investigating at some point (may be necessary to make swordless adult Link a thing to fix this????? I don't know????)

**Comment by Nax** [comment]
Likely fixed by the recent changes to swordless & age equips, reopen if the issue appears again.
