### ISSUE TITLE
Setting: Pre-Completed Dungeons needs to account for (plando'd) items on Dungeon Reward check?

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#502]
I believe you said currently pre-completed dungeons **does not** give you the item on the dungeon reward check (in this case, the blue warp item) and therefore right now you cannot have plando'd coins on blue warps and have those coins already given to you counting towards your (likely) coins special condition. Just putting this here so it's not forgotten, something you adjust for people to be able to make use of or for when one shuffles dungeon rewards to anywhere.

**Comment by Nax** [comment]
This was actually changed one day after release of pre-completed and now it works just fine.
