### ISSUE TITLE
Setting: Shuffle Freestanding Rupees and Hearts

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#514]
Title is self-explanatory. Shuffle the freestanding rupees and hearts (the ones you can actually **see** and aren't hidden/invisible) for both games.

- [x] OOT Freestanding Rupees and Hearts Shuffle
- [x] MM Freestanding Rupees and Hearts Shuffle

**Comment by CelestialKitsune** [comment]
Done in
- OOT: [86b242](https://github.com/OoTMM/OoTMM/commit/86b24277504cdbeef4f3cb77343831a8c900fd3d)
- MM: [62d747](https://github.com/OoTMM/OoTMM/commit/62d74729aaa475d82a81f8001f3db38bd8b53d1b)
