### ISSUE TITLE
Bug: Fog Glitch in Entrance Randomizer

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#522]
Title is self-explanatory. The fog glitch that normally happens in Lost Woods happens everywhere in Entrance Randomizer settings, specifically in OOT locations. This causes lighting distortions and graphical issues on emulator in certain areas (possibly also happens on console but not sure, according to Joshua on console the screen is just super dark?) You're aware of this issue but just noting here: it doesn't happen in OOTR's entrance randomizer settings at all, other than the normal Lost Woods fog glitch (which is still present in OOTR).

**Comment by Nax** [comment]
Should be fixed
