### ISSUE TITLE
Bug: Pot and Grass Shuffle in MM on Everdrive Issues

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#523]
You know what these issues are but basically if you collect some (or all?) items in certain areas in MM that have pots and grass shuffled, then come back later, and collect a non-shuffled item (or any of the items that you already grabbed from pots/grass) and then transform, the screen will stay white for a certain amount of time. Sometimes this eventually goes through but other times it can lead to a hard crash. See Jeville's posts here: https://discord.com/channels/1004394204992118935/1153765170691190825

Your most recent attempted fix did not work.

**Comment by Nax** [comment]
Finally fixed
