### ISSUE TITLE
Hints: Double and Triple hints should not count as WOTH

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#537]
I understand you had a good reason for this from a technical perspective (not wanting to retool/redo/rewrite code) but this is extremely confusing and not good for race settings. Most people coming from OOTR and MMR will be **very** confused when they see "Biggoron gives Blue Rupee, Ice Arrows (required), and Gibdo Mask (sometimes required)" then have a Death Mountain Trail WOTH and going by solo randos where sometimes and always hints **cannot** be WOTH they will assume the Ice Arrows on Biggoron is not the WOTH; but it in fact is. And they'll full clear DMT, using up time they otherwise wouldn't need to and that's really bad; especially in the case of Romani Ranch WOTH and Cremia having like, Fire Arrows (required) as another example.

This doesn't come up that often but this really needs to change.

**Comment by Nax** [comment]
Done
