### ISSUE TITLE
QoL: Disable Crit Wiggle in both games

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#538]
Title is self-explanatory. Remove the crit wiggle mechanic from both games, where you have low health (one heart generally) and the camera zooms in and Link randomly shifts left/right while you move in a direction. It's not a necessary mechanic at all and just messes with the player. You're already punished enough by being at low health.

**Comment by CelestialKitsune** [comment]
Done by [933a001](https://github.com/OoTMM/OoTMM/commit/933a00132ea631e23dfc40b3bf65993daab3cba4)
