### ISSUE TITLE
Setting: Sunlight Arrows in OOT

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#539]
Title is self-explanatory. Add an option for Light Arrows to activate Sun Switches. This would make LAs functionally in parity with MM as well as the Mirror Shields effectively (each Mirror Shield locking only 1 check lol). Since it's a setting like Blue Fire Arrows, it can be optionally turned on/off. The logic for this would be fun, especially in seeds where OOT Mirror locks LAs or LAs locks OOT Mirror in Spirit Temple.

**Comment by CelestialKitsune** [comment]
Done in [7a51d4c](https://github.com/OoTMM/OoTMM/commit/7a51d4c65a770f417cc0eefee7733f780c686b55)
