### ISSUE TITLE
Doesn't work properly with RetroArch, when using Mupen64Plus core w/ ParaLLEl plugin

### ISSUE THREAD

**Issue by 03bgood** [OoTMM/OoTMM#546]
I'm having major framerate slowdown when using "Synchronous RDP". If I turn it off, it runs fine. However, there are graphical framebuffer artifacts, like when text appears when talking to NPCs. Is there any way to fix this? The vanilla OoT ROM seems to run fine.

Also, framerate must be set to "Original", instead of "Fullspeed" or else the game will crash in OoT if the inventory menu is brought up while the minimap is enabled.

**Comment by Nax** [comment]
`ParaLLEl` is not supported (and IIRC it's no longer maintained).
The only supported configuration for RA is Mupen64Plus-Next with GlideN64.

**Comment by 03bgood** [comment]
It doesn't allow you to go from the Hyrule Market to Clock Town if it's set to "Gliden64". It just crashes to a black screen. This isn't an issue with ParaLLEl.
