### ISSUE TITLE
Bug: Fog Glitch still exists with Ravaged Village when you do not have Sheik's Soul (also happens apparently when you do)

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#555]
This was reported recently in the discord but apparently if you enter Kakariko Village with Forest/Fire/Water medallions without Sheik's Soul it still affects Kakariko's weather and will cause the fog glitch to occur into the **next** loading zones but *NOT* inside Kakariko Village. It's strange.

You can see it here: https://discord.com/channels/1004394204992118935/1009157440249536574/1172410058257219654

Just thought I'd add this here as I think someone else encountered this, too, so it is reproducible and frank there said the issue went away when he had Sheik's Soul.

**Comment by Nax** [comment]
Is this still an issue?
