### ISSUE TITLE
Setting: More "Open" Settings for OOT

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#556]
OOTR doesn't have these options but I think they should exist as they are equivalent in nature to Open/Closed Deku, Open Gerudo Fortress, and Fire Temple access as child and what not.

- [x] Open Jabu-Jabu - You do not need to feed Jabu the fish
- [x] Open Shadow Temple - All torches are already lit and the door is open
- [x] Open Bottom of the Well - The water is drained already as child (if adult access is turned on, obviously, the stone wall is gone as adult)
- [x] Open Water Temple - The gate is already up
- [x] Open Dodongo's Cavern (Child) - The massive boulder present as child is already blown up/gone.

These settings mainly could see use in ER. It's really strange how no one for OOTR has just done this considering I don't think these would be very difficult to implement at all?

**Comment by CelestialKitsune** [comment]
These should be rather easy to implement, I'll look into it

**Comment by Revvenn** [comment]
@CelestialKitsune Still interested in adding these? Just checking out older issues.

**Comment by CelestialKitsune** [comment]
Still thinking about how we should do all the open dungeon settings:
- in one set?
- own toggle as we currently have?
- something else?

Last discussion on Discord sort of lead to "set", but I'm not entirely sure if that's the proper way to go with this

**Comment by Revvenn** [comment]
> Still thinking about how we should do all the open dungeon settings:
> 
> * in one set?
> * own toggle as we currently have?
> * something else?
> 
> Last discussion on Discord sort of lead to "set", but I'm not entirely sure if that's the proper way to go with this

That's a good point. I think from a UI perspective having a drop-down and being able to select which ones are open/closed makes sense. I also think that given the changes to Deku Tree's behavior it being its own option separate from the others makes sense at the same time. Before, when we discussed the possibility of a set, Deku Tree only had Open/Closed. But now it has Open/Vanilla/Closed which does not mirror the other dungeons (which are simple Open/Closed options). As a result, I think we could easily do a "set" now without Deku Tree and thus without impacting any presets or current players' setting strings.

Also, I need to add Child Dodongo's to this list so Dodongo's Cavern can have the option to have the boulder gone as child... It'd make sense... I think...

**Comment by CelestialKitsune** [comment]
Done in https://github.com/OoTMM/OoTMM/commit/29e0c5a47e87562d3b2818bf5b31a0ac87fd4a25
