### ISSUE TITLE
Unbeatable Seed (No way to get Bombchus in MM without 4th wallet in OoT; which is out of logic)

### ISSUE THREAD

**Issue by 03bgood** [OoTMM/OoTMM#561]
[OoTMM-Spoiler-492ksBmn.txt](https://github.com/OoTMM/OoTMM/files/13342915/OoTMM-Spoiler-492ksBmn.txt)

I cannot get the 3rd wallet upgrade (OoT) because the Bombchus for MM cost 735 rupees in the Kokiri Shop and I can only hold 500 rupees, currently. Also, cannot warp from MM to OoT unless I'm a child. I currently have no Ocarina in OoT, just MM. Also, The OoT wallet upgrades for (999-9999 rupees) are out of logic. The only glitch I know is the Goron bomb one for getting into Great Bay and Ikana, without the use of Epona and there's no Ocarina for OoT or any Hookshot (OoT or MM) in either of those areas. What am I doing wrong? I have all the enemy and boss souls I need and can afford. Also, can't get to inverted Stone Tower from DMC because I'm a child (gray boulders) and there's no way to warp from MM to OoT as an adult since the market mask shop is no longer there as an adult. "Honey and Darling Day 2" only gives me a purple rupee (50), instead of Progressive Goron Lullaby (Needed to get into Pirate's Fortress where Progressive Ocarina and Hookshot for OoT are) because I have to beat "Day 1" with Bombchus and there's no "other" way to get them AFAIK. Seed cannot be beaten and this is using "glitchless" logic.

**Comment by Revvenn** [comment]
Nax and I have told you countless times to join the discord first to get help with something you _may_ be missing with logic. This is very unlikely to be an actual logically impossible seed. If you have everything up to Sphere 5, you can do the Goron Keg Trial in the North with Goron Mask to access the Goron Racetrack and you will find your item in the zillion pots there you need to be able to get Honey and Darling Reward 2 (completing all 3 days). From there, it's as simple as following that song. You don't need to go adult right now based on what I'm reading in the log.

However! This is still a recommendation and preference to just join the discord (https://discord.gg/4QdtPBP6wf) and ask in the #help-me channel before reporting potential logic problems. This just seems like you didn't know you can use the Powder Keg from the Goron Keg Challenge/Trial in Goron Village to access Goron Racetrack in the Winter. This is not a logically impossible seed.

Once again, this github is for **confirmed** bugs. Please stop making issues for things that aren't **confirmed** bugs.
