### ISSUE TITLE
Bug: Song of Double Timing after Song of Timing in areas that do not have "Dawn of X Day" can softlock in ER

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#564]
Title is self-explanatory. When you set your spawn in MM from say, Swamp Spider House (say you checked the dungeon and then went back) and then you later finish your cycle and Song of Time it will put you back in front of Swamp Spider House (as it should). However, if the player **immediately** Song of Double Times then it can lead to them getting softlocked **OR** push their day to day 2 instead of night 1. I told you about this months ago from TheWayFaringFox warning me about it in DMs but because there were so many other bugs it was lower priority to fix but I think now it makes sense to address it.

**Comment by Nax** [comment]
Should be fixed, reopen if it comes up again
