### ISSUE TITLE
Bug: MQ Wall Cow where Ruto spawns can be milked for the MQ Jabu Cow's item further in the dungeon

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#571]
Title is self-explanatory. Apparently you can milk the wall cow in the room Ruto spawns in to get the MQ Jabu cow's item **further** in the dungeon (past the Big Octo). Should probably be prevented somehow (maybe just make it give milk? Or just restrict it somehow). Reported here: https://discord.com/channels/1004394204992118935/1004394205478662156/1174741399183302727

**Comment by Nax** [comment]
Fixed
