### ISSUE TITLE
Website Bug: Custom Models erroring when putting in a new one after getting "Invalid Model" error

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#572]
You already know about this but I'm putting this here because you keep saying "I need to fix that" and then you don't lmao. Basically, when you get the "Invalid Model" error, if you put in different custom model files in to try again it'll spit out **another** error preventing you from genning even if the models put in **do** work. You have to refresh the page to fix this. It makes trying out different custom models cumbersome on the end user.

**Comment by CelestialKitsune** [comment]
Fixed in [36547f](https://github.com/OoTMM/OoTMM/commit/36547f0e758c8edb9d8dbf59deeb7a7f7ec50f87)
