### ISSUE TITLE
Bug: Goron City in OOT with Custom Music breaks with certain songs

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#579]
Unsure how to really describe this succinctly but basically if you have a song that is too large (?) in Goron City, it will just instantly break upon entry into the area and you will have no music at all in there. Something is up with the audio engine for custom music anyway in this area and also sometimes in interiors. Unsure on what the solution is as I can't find a PR for something like this for OOTR. Might have something to do with Goron City being near Lost Woods and whatever song lands at Lost Woods, when transitioning to Goron City or being **near** that transition overloads the engine and kills the BGM in Goron City?

**Comment by CelestialKitsune** [comment]
Mentioned by OwlIsNotACat on Twitch: audio heap was not resized.

**Comment by Nax** [comment]
Should be fixed
