### ISSUE TITLE
Bug: Fanfares break Custom Music

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#580]
Title is self-explanatory. Fanfares in both games kill Custom Music due to the audio engine getting overloaded, I think. Owlisnotacat has a PR for OOTR that fixes this issue here: https://github.com/OoTRandomizer/OoT-Randomizer/pull/2050

Although, unsure if it fixes it for vanilla fanfares or not.

I also don't know what MMR does to prevent fanfares killing music in MM but for 1.16 Zoey added an option to just disable fanfares completely and use some kind of minor-pick-up sound effect fanfare instead. Perhaps something we will want to add as an option instead? Or just add the option to disable Fanfares for both games anyway? And apply the same sound effect seen in MMR 1.16 (when it's out of beta).

**Comment by Nax** [comment]
Should be fixed (not 100%), reopen if issue persists
