### ISSUE TITLE
Bug: Arrow Cycling in OOT with Chateau Magic visually breaks

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#581]
Title is self-explanatory. Basically, when you arrow cycle while having Chateau Magic in OOT the magic bar still decreases and increases. As a result of this, when the magic refund happens you can exceed the magic bar graphic. It doesn't break the game in any way, it's just a visual issue. Just needs to be made so it doesn't increase/decrease like in MM.

**Comment by Nax** [comment]
Fixed
