### ISSUE TITLE
Issue with logic for OOT Goron City Big Pot

### ISSUE THREAD

**Issue by frizzle101101** [OoTMM/OoTMM#591]
I seem to have found a seed where the path is blocked by needing to get a critical path item from the OOT Goron City Big Pot but I cannot open the pot as I have no access to the fire yet in Goron City.

[OoTMM-Spoiler-7G8x1XUX.txt](https://github.com/OoTMM/OoTMM/files/13688402/OoTMM-Spoiler-7G8x1XUX.txt)

**Comment by Nax** [comment]
Please use the discord server for that, the github issues are not for getting help on seeds.
