### ISSUE TITLE
Grass in Gorman Track impossible to access without tricks?

### ISSUE THREAD

**Issue by HaydnVH** [OoTMM/OoTMM#593]
I have Shuffle Grass enabled for both OoT and MM.  According to the spoiler log, my Goron Mask is in one of the grasses on Gorman Track.  I can reach the grass in question during the race with the brothers, but I cannot pick up items dropped by grass while riding Epona, and I cannot dismount Epona during the race.  To my knowledge, it is impossible to access this grass in Gorman Track without either being in the horse race, or the milk cart sequence, during both of which I cannot pick up items dropped by the grass.  I could probably get around the fence using a hover or weird shot or something, but I don't know how to do those tricks and do not have them enabled in the logic settings.  Is my seed impossible or am I missing something?

Settings export: `v1.eJx9ls1ymzAQgN+Fc56gt9iJnTR10ynMeKY3AWtQEVpGP6Vup+/elbAtCXBu5tuVtP/rv5nAhlfZp6wEZlgpIHvINMpGE2LyPLagHGpQ1HlnhTBWsAI7kF5BCJK1aDXoe1LDZSMgb+3pRJcnl/Zs2GI/MK1XxbqnG97gfBG+o/lQfug/FL/wGtDOrihR6w9eSMX3HvhOHvqjfzNzHpwTiska++xfquPOr6kYxc47xtX53dDNIRQ4yicrG0DpHquULWM7jbKQYnf/RCscl6oBBkXd4pA4f7I+aRH3Xl8wjmI9UxP8hkbHtgUav+jhXlHWl7oeL5QPoKqWyfiaAWW947q9mTNhaJoZGRSvnG85eeSKcgTetAbqLBK5GK7JDv29U4e+8GWdihomURaKM6HvZJop1w6PTcQfMtbAltzzECkkD1kNnS0UOFAJ1P7yK3usrbiFbQQhEnDiii7jor6CP6jYG73pEuYVyYyODz9A1Ox2iK7NK6agUjjGFaOo/o9MDWssrotSMG0OTHdbpDlBdUsiKiHlXjtxyh48ATfnx2vF3IwV4kj9AUaHdGGjQGv+i0YGJyOnIol5tqblrbmrtN/lC3GJxgjYojQgzaxotJU5Tg17sdS3J4WISxZoKSzsKOCPiuKmo55S5gWxox8m6kmXlZm3FVJ2NZsHwZmGvQAX6ESgO6BPlDRQ4t4JNDyHk7EbS1dJvZwGq/Ko89AK/SyhTx66wZniBtNmvrKg1oO0X9FASXEJgaKSq79ao3PDq06nfJOEdCJ9uWHNjB6Y318L5JPisnNP9lrdFX1xLZ0KXT0809RhS5wbVL1e8oL3sKJtZQqvpZLSL36HxuRSfnObdbdHhXKJf1DnL+nGSnle4jfa/muXFMqaNsXzmpycACbmivmtXFYduZTe7Eyo5auAxqNrhXxEVes5nLp/RgsreTWHGxqti+NJ3QXFHmg4NzP+wnriczhL3gX7EVwoVofNpFxDhJEJ6rLbE3ZgPzESXI8euFzDe7dvtjR6owU4wQLHYCqdx5Bb+ocx0F8h9eL/tQX6jStmYEezy83IyGyQVBvtkTZNgK8dk2z+ck77A2iUUnIj+kpbDlXi5QV5ZxeKz79NqFtQbtUkh98lHNl5Db2P4mZ3ffnjRGv4qYiX7dM2/vr8Of4i50GbhPj5Eb6PFCIVA4ql4smRvGW0AWOyQXOMv18TE/bFPvl06Yv+Nfz7D8SxLb4=`

Spoiler log:
[OoTMM-Spoiler-2KA6XgwQ.txt](https://github.com/OoTMM/OoTMM/files/13694981/OoTMM-Spoiler-2KA6XgwQ.txt)

**Comment by Nax** [comment]
You need to go to the gorman track without being in a minigame. You can do that with a goron bomb jump (trick), or by doing aliens, which will change the layout of Milk Road on day 2 (or night 2, can't remember), which is how to get there without any trick.

Next time please ask these kinds of questions on the discord instead, as we don't normally answer logic questions here.

**Comment by HaydnVH** [comment]
I can't get the Goron Mask because that's what's in the grass in question.  I can't do aliens without blowing up the boulder using a powder keg, which requires Goron Mask.  I can't do a goron bomb jump without Goron Mask (and even if I could, as a trick, I should need to enable that in the settings logic).  This is a logic error.

**Comment by Nax** [comment]
It's not. You can get to ranch via ER.

But again: **ask these kinds of questions on the discord instead, as we don't normally answer logic questions here**
