### ISSUE TITLE
Vanilla Bug: Hover Boots in Slingshot/Bow Slot in OOT

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#603]
Title is self-explanatory. In vanilla OOT, when you go adult without having slingshot the game puts Hover Boots there instead. It's only a visual bug and fixes itself once you have the proper item in that slot but new players ask about it or get confused often about it so it should probably be fixed. OOTR fixed it... Ah, yes, here's the PR for it: https://github.com/OoTRandomizer/OoT-Randomizer/pull/436

**Comment by Nax** [comment]
Fixed
