### ISSUE TITLE
Setting: Start With Pre-Completed Dungeon Boss Souls in Boss Soul Shuffle

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#604]
Title is self-explanatory. Dungeons that are pre-completed means you should start with the respective dungeons' boss souls. If you have Deku Tree pre-completed then you should start with Queen Gohma's Soul. The reason this shouldn't apply to enemy souls is because enemies are everywhere in the overworld so it'd make pre-completed dungeons override the point of soul shuffle. Bosses are more unique and nothing sucks more than seeing a Boss Soul on like, Ikana Canyon ledge and going to go get it and it is one of the boss souls **you don't need**.

**Comment by CelestialKitsune** [comment]
Done in https://github.com/OoTMM/OoTMM/commit/b862cd368d8607f288df5f110a6c2af2ee52d9b5
