### ISSUE TITLE
Looping day cycle

### ISSUE THREAD

**Issue by keanine** [OoTMM/OoTMM#605]
I'm not sure how realistic this suggestion is, but it would be really cool to have the option to loop the cycle in MM. So instead of the world ending on the final day, it just loops back round to day 1. I imagine this would be a fairly big feature as it would affect seeds due to Ocarina & Song of Time not being required

**Comment by Revvenn** [comment]
The github is not for general suggestions. They are for confirmed suggestions/plans acting as sort of a roadmap. You can suggest this on the Discord and receive feedback regarding the idea and whether people like it or not.
