### ISSUE TITLE
Incorrect item in check

### ISSUE THREAD

**Issue by AkariEnderwolf** [OoTMM/OoTMM#606]
So, I'm playing with shared Ocarina of Time turned on, and checked my spoiler log. it claims that there was a Progressive Ocarina at the Adult Link shooting gallery in Kakariko Village. I went to the location and instead of getting an Ocarina upgrade from completing the minigame I got a Purple Rupee. The game seems to be acting like I already got the prize when I didn't.

**Comment by AkariEnderwolf** [comment]
I redid the minigame, it's acting like I already got the check when I didn't. I found some gameshark codes that give the item I was missing because of the issue, I just wanted to bring attention to it.

**Comment by Nax** [comment]
You probably lack the bow - the adult gallery gives a purple in this case, this is vanilla behavior and intended, logic takes that into account.
