### ISSUE TITLE
Bug: Buying multiple beans from the Southern Swamp scrub in Co-op has issues

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#637]
Basically, you can buy one bean from him just fine but buying subsequent beans results in getting the Nothing item in co-op seeds. Only way in  co-op to buy more than one bean in a cycle is to go to the Bean Salesman in Deku Palace which reportedly works fine in co-op. Supposedly this issue also exists with the Milk Bar and Chateau Romani?

**Comment by Nax** [comment]
It should be fixed with the recent renewable fix - reopen if issue persists
