### ISSUE TITLE
Setting: Stone Mask in OOT + Shared Stone Mask

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#644]
Title is self-explanatory. Stone Mask in OOT would make most enemies ignore you except the following:

- Deku Babas
- Dinolfos
- Elite Gerudos in Gerudo Fortress
- Flare Dancers
- Gibdos
- Iron Knuckles
- Like Likes
- Octoroks
- Poes
- ReDeads
- Stalchildren
- Stalfos
- White Wolfos
- Wolfos

And that's it.

**Comment by Nax** [comment]
Added
