### ISSUE TITLE
Bug: Transforming into Deku while playing Honey & Darling on Days 1 and 2 turns B button into a Deku Nut

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#663]
Title is self-explanatory. The issue is that your sword cannot be restored once this happens (Song of Time doesn't work, getting on and off of Epona doesn't work, and playing the mini-game again doesn't work either). So the proposal is to restrict D-Pad use **during** the mini-game state for Honey & Darling and the Archery mini-games in MM.

**Comment by CelestialKitsune** [comment]
Done in https://github.com/OoTMM/OoTMM/commit/06f0b102ff705e5a1b6b01985bac3e763d24ee53
