### ISSUE TITLE
QoL: When New Cycle Moon is turned on, speed up the Moon Crash cutscene

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#696]
Title is self-explanatory. Shuffling away Song of Time and having to watch this cutscene go all the way through adds a lot of time to the seed over time. Cutscene should either be removed or just sped-up in some fashion when New Cycle Moon is enabled.

**Comment by CelestialKitsune** [comment]
Will eventually be done once I figure out which actor is responsible of the cutscene (but not a high priority, so watch the world burn in the meantime!)
