### ISSUE TITLE
Bug: Goron Ruby's model materials when not on a blue warp in MM are not correct

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#699]
I told you this in DMs but wanted to put it here so it's not forgotten. It's really weird but when Goron Ruby is found *anywhere else* in MM, its shading is darker than normal overall and looks grainy; the materials are messed up in the same way the Bombchu Bag model was for a little bit or the Scales and the OOT Mirror Shield. Basically how it looked before you fixed how dungeon rewards looked in MM over a year ago? But for some reason it only applies when the Goron Ruby isn't on a blue warp in MM. And yes it **is** only the Goron Ruby and not any of the other dungeon rewards, not even the other 2 stones.

**Comment by Nax** [comment]
Fixed
