### ISSUE TITLE
Bug: In Clock Shuffle, Double Timing in areas *without* "Dawn of X Day" transition Night 3 Clock issue

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#700]
Basically, if you try to Song of Double Time in Southern Swamp, inside grottos, inside the Ikana Graveyard graves, etc and you recently **found** Night 3 Clock (or just obtained it at all), instead of transitioning to Night 3 like it's supposed to it instead goes to Moon Crash for some reason.

You can see this bug report here: https://discord.com/channels/1004394204992118935/1223834761303294104/1224857319075217469 (Ghunzor also reported it as you can see the thread itself lol).

**Comment by Nax** [comment]
Should be fixed by the recent rework, be sure to report any bug that might still be there
