### ISSUE TITLE
Bug: logic requires one way teleport with no way to escape moon crash?

### ISSUE THREAD

**Issue by Blackwolf291** [OoTMM/OoTMM#701]
Attached spoiler log.
[OoTMM-Spoiler-q63ZKpgD.txt](https://github.com/OoTMM/OoTMM/files/15003357/OoTMM-Spoiler-q63ZKpgD.txt)
This seed seems to ask i song of soaring into MM's great bay with no way back out, as majora fairy ocarina is disabled.
This means that even though i get a teleport song, i have no valid path back out, and the only path out is out of logic by racing back against the moon crash, which is not impossible, but seems not logically valid.

**Comment by Nax** [comment]
Doesn't matter that you have no way back as you can savewarp.
