### ISSUE TITLE
Bug: MM Only has issues genning with Blast Mask check junked

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#705]
Title is self-explanatory. If you junk the Blast Mask check in MM Only seeds, it gives the error "C is not iterable." I was able to figure this out because I was trying to recreate MMR's blitz settings in combo and those settings basically make the whole All Night Mask purchase sequence junk in favor of keeping Letter to Kafei (because you can just push those checks as soon as you have Letter, while the ANM Purchase sequence requires you to wait for night 1 midnight then commit to final night 10 pm etc it slows seeds down to an extent in solo MM). When I unjunked this check, the settings I had rolled with no issues but when it was re-junked it gave the error again.

**Comment by Nax** [comment]
Is this still an issue?

**Comment by Revvenn** [comment]
It is not an issue, I might have been trying it with pre-completed dungeons when that was broken and so when I unjunked the check it was just coincidence that it didn't try to roll any OOT dungeon pre-completed in MM Only I guess lol. Closing. (I tested it, no issues).
