### ISSUE TITLE
Bug (kind of): Actors not filtered properly in NPC Soul Shuffle

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#706]
Title is self-explanatory. There's a few OOT and MM actors not filtered out or filtering properly, these are:

- Punk Kid in Child Kakariko Village, he is there without Punk Kid soul
- Romani in Romani Ranch on Day 2 (after Aliens sequence, when she's been abducted). She is there when you don't have the soul. Might be other instances but this is the instance that was called out.
- Trading Post Part Timer in Termina Field in the tree, during the day he is trying to grab rupees from the tree by the Observatory (the red rupees by the Termina Field scrub grotto). He is there when you don't have the soul.
- Running Man in OOT (should be filed on Citizens like Postman in MM to have them properly synced as currently they are not).

I believe these are the current actors not filtered out properly or somehow being missed. Might be one more I'm forgetting, unsure. But these are the three that have been found.

**Comment by AndrewMDelgado** [comment]
Super niche case in entrance rando, but Romani's also in the barn on Night 1 waiting out Them.

**Comment by CelestialKitsune** [comment]
Tried to reproduce Romani spawning despite not having the soul without success. She's never been there without her soul on my end.
Fixed most of this in https://github.com/OoTMM/OoTMM/commit/a25abcd1da5e7b4d6d1cfacfc606b63678078488
