### ISSUE TITLE
Bug: Putting on Giant's Mask in Twinmold's arena without Twinmold's Soul causes a softlock

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#708]
Title is self-explanatory. This has been a bug for a long time and I kept forgetting to put it here (obviously in favor of more, higher priority crashes/softlocks). I was reminded of this softlock in #play-by-play in the discord tonight. Basically, putting on Giant's Mask in Twinmold's arena without Twinmold's Soul will have Link initiate the Giant's Mask transformation cutscene BUT then it won't continue, you will be stuck just before he's about to finish the transformation. Not sure if you can even pause during this (I don't think so) so you can save warp.

**Comment by CelestialKitsune** [comment]
Done in https://github.com/OoTMM/OoTMM/commit/687db65a2baeedfec26c450c5181c9eb7ab746a0
