### ISSUE TITLE
Bug: Talking to Carpenters/Guards in the Mayor's Office without Mayor Dotour's Soul Crashes

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#711]
Title is self-explanatory. Probably just need to make it so you need both Carpenters Soul and Mayor's Soul to spawn all actors to prevent players from talking to NPCs that will result in a crash due to the Mayor actor not being present.

**Comment by CelestialKitsune** [comment]
Should be fixed by https://github.com/OoTMM/OoTMM/commit/2206cfb399d442af2b2b0c98016b1036779a7e1e
