### ISSUE TITLE
Bug: Some music is not shuffled that was shuffled previously in Custom Music

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#727]
I told you this in DMs today, just putting this here so it's not forgotten. Basically, three songs are not shuffled that were before:

1. Ganon Boss Theme (the final boss in OOT)
2. Milk Bar (it's shown in cosmetic logs as shuffled but for some reason the song is not actually shuffled in-game)
3. Gerudo Training Grounds/Dodongo's Cavern are not shuffled (they share the same song)

Unlike Milk Bar, GTG and Ganon Boss Theme are **not** shown in the cosmetics log.

That's all.

**Comment by CelestialKitsune** [comment]
Done
