### ISSUE TITLE
Bug: Slight item collection delay with Death Mountain Crater song

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#733]
Title is self-explanatory. For whatever reason, the Death Mountain Crater title card causes some item collection delay in DMC. As you cross over the bridge for the song (or item if it's songsanity) you won't receive the song/item and will continue to walk right by it. You can go back and run over the trigger spot to actually _get_ the song/item but as long as the DMC title card is on-screen you cannot/will not receive the song/item when you walk over the Bolero song trigger.

This doesn't happen in ZOOTR, even if you force start with a song to skip song input cutscenes.

**Comment by Nax** [comment]
Fixed
