### ISSUE TITLE
Bug: Got a deadlock when opening chests

### ISSUE THREAD

**Issue by Finalrykku** [OoTMM/OoTMM#734]
Hi,

great work, I love this ootmm, but I got a deadlock in the newest version:

[OoTMM-Spoiler-X301N7hl.txt](https://github.com/user-attachments/files/15518048/OoTMM-Spoiler-X301N7hl.txt)

Visit the first house with the four chests. Two of them freezes the game. 
After opening the first one (OOT Mido's House Top Left: Nothing), no message appears and the game freezes, in another chest ( OOT Mido's House Bottom Right: Silver Rupee (Ganon's Castle - Spirit Trial)) I see a silver rupee before the game freezes

Best regards

**Comment by Revvenn** [comment]
Please join the discord https://discord.gg/4QdtPBP6wf , the github is not for posting issues like this.
