### ISSUE TITLE
Bug: Romani Ranch boulder is gone if you spawn in Milk Road at the start of day 1 before 6 am

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#736]
Title is self-explanatory. eedfeede was the first person to find this and I went to test it today in my seed to confirm it with just Dungeon ER and Boss ER active. Basically, if you set your spawn in Milk Road and then do any form of time reset in MM (Song of Time or defeating Majora) when you respawn back in Milk Road, the boulder for Romani Ranch will be gone. This is ER only because your spawn can only be changed with ER enabled so something caused this to happen recently. It **will** come back if you exit Milk Road and then come back into Milk Road so it's not a flag issue where it's permanently gone.

Clip: https://clips.twitch.tv/PolishedAltruisticPidgeonKappaClaus-6dDw1uHUWUt__24V

Edit: It would appear that this isn't ER-only. If you song of time after getting Milk Road Owl Statue and then reset (when the Song of Time cutscene is playing) and then soar from OOT to Milk Road, the boulder will not be spawned. Likewise, in Owl Shuffle, if you start with the Milk Road Owl Statue and then soar to Milk Road immediately it will also not be present. It's all the same issue, however.

**Comment by CelestialKitsune** [comment]
Seems to be caused by simply getting to Milk Road on Day 0, can happen in many ways:
- owl shuffe + cross warp (without ever setting foot in MM before)
- soft-reset after song of time then warp
- altering your spawn MM spawn (ER)

**Comment by Nax** [comment]
Fixed
