### ISSUE TITLE
Bug: Random extreme lag in some places (Mountain Village Spring Time tunnel, Mayor's Office?)

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#751]
Title is self-explanatory. Unsure what the cause is but ghun apparently experienced lag on emulator in mayor's office while I experienced extreme lag on N64 in the Mountain Village spring time tunnel. You can see that here: https://clips.twitch.tv/BusyBeautifulCurryGrammarKing-TdVnNxkcJ1rtAHKF

**Comment by CelestialKitsune** [comment]
Fixed by https://github.com/OoTMM/OoTMM/commit/886dfaf1f06d4a3bac4f3701ef5b8a59f572c895
