### ISSUE TITLE
Bug: Kokiri/Master/BG/Razor/Gilded Sword deletion upon leaving Bombchu Bowling with Chus on B in Entrance Randomizer

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#772]
Title is self-explanatory. I believe this is the cause as it doesn't appear to happen with either Kokiri Sword or Master Sword or GN/BGS and I think this can only happen in ER because it requires chu bowling to lead to MM in some fashion when you exit. It only appears to happen with the newly added Child Swords. It happened to usedpizza last night: He had OOT Bombchu Bowling in the Ikana Graveyard entrance in Road to Ikana. He walked in, bought round 1 bombchu bowling **as a child**  (he's not adult and no ageless swords enabled) saw it was junk and spammed chus away to go to round 2. Upon seeing round 2 was junk, instead of getting rid of Bombchus on B by ending the mini-game the same way instead he left the building with Chus on B going to MM (since the entrance was in MM). A LOT of people handle Bombchu Bowling this way, they leave with Bombchus on their B button. The next time he entered OOT, his B button was sticks (as you'd expect) **BUT** his Gilded Sword was gone.

All other cases of this have been explicitly Razor and Gilded, I'm 100% convinced it's tied to those upgrades and does not occur with Kokiri, Master, GN/BGS because of how you wrote the swordless flags for those swords and the swordless setting came _before_ you added the extra child swords. And you only rewrote the swordless flags a little while later, I'm unsure if you actually did this when the other swords were added but I don't think so since they came when you were doing all the other Ageless items.

Regardless, this _should_ be reproducible if you plando Bombchu Bowling to be at an MM entrance and walk out with chus on B with your Razor or Gilded Sword equipped. I'm unsure if age matters (but it probably doesn't?)

I should also note, not that it matters for this, but usedpizza did have the bow already and he obviously had not ridden Epona yet (as he didn't have Epona).

Edit: Per Celeste's testing below, this affects **all swords** so long as you exit bombchu bowling with the appropriate sword equipped and chus on B _if_ bombchu bowling goes back to MM directly (thus, inducing a save).

**Comment by CelestialKitsune** [comment]
Did some testing:
Save resetting with Stick on B is what deletes the sword.
Getting Stick on B is also 100% reproducable - have a sword equipped, start minigame, leave minigame
