### ISSUE TITLE
Ice Cavern: Block silver rupees softlock

### ISSUE THREAD

**Issue by CelestialKitsune** [OoTMM/OoTMM#782]
Collecting the last silver rupee of a puzzle _inside_ of said puzzle room, while airborne softlocks as shown as in this clip https://www.twitch.tv/revven91/clip/SpoopyObliviousNarwhalRedCoat-rlUQhQMgtXMr03Nl

**Comment by Nax** [comment]
Yeah this is because the camera kills the textbox, so we never unfreeze the player when closing the textbox normally, annoying to fix.

**Comment by CelestialKitsune** [comment]
> Yeah this is because the camera kills the textbox, so we never unfreeze the player when closing the textbox normally, annoying to fix.

I think I found a fix, which was not too annoying to put in place: it involves editing the condition englobing the global delayed switch flag, by checking if Link's state is "jumping". Let me know what you think of it @Nax

**Comment by Nax** [comment]
Sounds good, can you prep a branch?

**Comment by CelestialKitsune** [comment]
> Sounds good, can you prep a branch?

https://github.com/OoTMM/OoTMM/tree/sr-fix

**Comment by CelestialKitsune** [comment]
This also happens when NOT airborne. We need to find a fix for this

**Comment by CelestialKitsune** [comment]
Should be fixed by https://github.com/OoTMM/OoTMM/commit/f9cce68b005e5d3f069903a6bfd608943d0f008d - repoen if it reoccurs
