### ISSUE TITLE
Setting: Randomize locations of individual notes for songs.

### ISSUE THREAD

**Issue by ebrown38** [OoTMM/OoTMM#800]
There is currently a setting in the randomizer where the player has to find notes for an ocarina to be able to play those notes. For example, C-up, C-down and the like. Until you find those notes, you can't play songs that have those particular notes, even if the song is unlocked.

This would be an even more advanced setting to this in which the player needs to find ALL the individual notes for each song as their own items. Only after they find all the notes will the song be unlocked for play.

For example, in order to play song of storms, the player would need to find 1st A, 1st C-down, 1st C-up, 2nd A, 2nd C-down, 2nd C-up and only when all those notes are collected is the song unlocked.

**Comment by Onemario1234** [comment]
Please post suggestions in the #suggestions channel of the Discord server, not here.
