### ISSUE TITLE
QoL: OoT Allow Warp Songs and Farore's Wind in Additional Places

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#87]
Basically what the title says but here's where it should specifically apply to for both:

Gerudo Training Ground
Inside Ganon's Castle (Trials)

Here is the PR for this from OOTR: https://github.com/TestRunnerSRL/OoT-Randomizer/pull/730

You can also read further down why they didn't touch Windmill/Dampe's Grave and Treasure Chest Game.

**Comment by Nax** [comment]
Added
