### ISSUE TITLE
QoL: OOT and MM Elemental Arrow Cycling

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#90]
Basically what the title says. I think it should apply to both games, when you aim with the bow (and draw an arrow) press R to cycle through the elemental arrows you have (Fire > Ice > Light). 

Here's the MMR ASM on its implementation if it helps: https://github.com/ZoeyZolotova/mm-rando/blob/dev/assembly/c/ArrowCycle.c
https://github.com/ZoeyZolotova/mm-rando/blob/dev/assembly/c/ArrowCycle.h
https://github.com/ZoeyZolotova/mm-rando/blob/dev/assembly/c/ArrowMagic.c
https://github.com/ZoeyZolotova/mm-rando/blob/dev/assembly/c/ArrowMagic.h

For OOT you may need to make the elementals not drain magic when you are "pulling" them out, they should function like MM's eles where they only drain magic when actually shot (in order for this feature to work properly for OOT). Edit: At least, I think that's how MM eles work? Unless I'm confusing it with Cat's changes for elemental arrow cycling in MMR to begin with lol. 

- [x] OOT Elemental Arrow Cycling
- [x] MM Elemental Arrow Cycling

**Comment by Nax** [comment]
Done
