### ISSUE TITLE
QoL Setting: Free Scarecrow Song

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#93]
Basically what the title says. You do not have to set Scarecrow Song for the OOT Scarecrow or the MM Scarecrow when this is toggled to on. It's a setting rather than baked into the randomizer because no one can predict the future on what settings people will inevitably play/race with.

How it works: You pull your Ocarina out near a Scarecrow spot and the Scarecrow is triggered to spawn.

I can't find a commit for Free Scarecrow from OOTR but for MMR here's how they set it up: https://github.com/ZoeyZolotova/mm-rando/blob/dev/assembly/c/Scarecrow.c

- [x] OOT Free Scarecrow
- [x] MM Free Scarecrow

**Comment by CelestialKitsune** [comment]
Done in https://github.com/OoTMM/OoTMM/commit/cd8543cfac9395346efb8e791ed8a29b04358a43
