### ISSUE TITLE
OoT Setting: Closed Deku Tree

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#96]
This is a somewhat popular setting in OOTR. Basically, Mido will block the Deku Tree until you show him the Kokiri Sword and Deku Shield but you still can leave the Forest like normal. This gives value to the Kokiri Sword outside of combat situations and it also pushes Deku Tree to be later in seeds, which does matter for your goal settings if you're playing with say, 5 Dungeon Rewards required for Ganon's Castle access. Granted, this is a different randomizer since Dungeon Rewards and Remains are all shuffled around... it should still be a setting available.

Simple drop-down: 
Open Deku Tree (current behavior) 
Closed Deku Tree

OOTR PR for it: https://github.com/TestRunnerSRL/OoT-Randomizer/pull/662

**Comment by Nax** [comment]
Added
