### ISSUE TITLE
QoL: OoT Faster Silver Boulder Lifting and Gold Gauntlet Boulder Lifting

### ISSUE THREAD

**Issue by Revvenn** [OoTMM/OoTMM#98]
Found the PR for this while trying to look for Twinrova intro cutscene stuff (couldn't find it).

https://github.com/TestRunnerSRL/OoT-Randomizer/pull/1122

**Comment by CelestialKitsune** [comment]
About time we close this one eh. Done in [8b90879](https://github.com/OoTMM/OoTMM/commit/8b9087985080f9b7a89f5657c4f87ef4bd6e2366)
